### ISSUE TITLE
when are you releasing this plugin

### ISSUE THREAD

**Issue by hsmith825** [naoufal/react-native-payments#1]

**Comment by lrettig** [comment]
Take a look at https://github.com/lrettig/react-native-stripe. Inspired by this module but with a slightly different approach.

**Comment by hsmith825** [comment]
Hi Irettig,

I am inteerested in trying the react-native solution.  In looked over the documentation and hI have two questions.
1. I am assuming I will not need to learn React ?
2.I am not certain what the Library Group refers to in "Drag StripeNative.xcodeproj into your Libraries group ".  Are you referring to the Directory of Frameworks in Xcode?

Thanks!

**Comment by masterkrang** [comment]
@lrettig i'm going to take your advice since it looks like this repo isn't active anymore. any advice @naoufal ?

**Comment by lrettig** [comment]
Hi @hsmith825, sorry I missed your question. If your question is about this repository, you should aim it at the repo owner. If it's about my repository (linked above), please post it there. Thanks!

**Comment by naoufal** [comment]
I was waiting for the right API to release this library. Ended up changing the API to match the payment request API and released the library yesterday.
