### ISSUE TITLE
How to do automatic billing using this library?

### ISSUE THREAD

**Issue by jojonarte** [naoufal/react-native-payments#101]
I'd like to implement an automatic billing for every month, is that possible?

**Comment by Andreyco** [comment]
Yes, it is possible. I successfully submitted app with support for recurring payments. I described flow (for Braintree) [here](https://github.com/naoufal/react-native-payments/issues/29#issuecomment-340225880).

**Comment by jojonarte** [comment]
@Andreyco  Is there an equivalent to metered usage billing from Stripe, in Braintree?

**Comment by Andreyco** [comment]
Not sure, never used stripe service before
