### ISSUE TITLE
Stripe link in README broken

### ISSUE THREAD

**Issue by tmaly1980** [naoufal/react-native-payments#11]
The readme links to a Stripe addon, and the URL goes to a 404 page:

https://github.com/naoufal/react-native-payments/blob/master/cli/packages/react-native-payments-addon-stripe

**Comment by naoufal** [comment]
Thanks for pointing that out!

Here's the link you're looking for https://github.com/naoufal/react-native-payments/blob/master/packages/react-native-payments-addon-stripe.

This would make for a great PR if you're up for it.

**Comment by andrerfneves** [comment]
Went ahead and created the PR
