### ISSUE TITLE
Payment Sheet did not Show

### ISSUE THREAD

**Issue by SimoneLSK** [naoufal/react-native-payments#115]
Hi there, 

may I know if anyone has problem with unable to show Payment Sheet on AN after execute **PaymentRequest.show()**

below picture is what i have got from the console.log, which there is no **show()** function, 
may I know if it is the main reason why there is no payment sheet pop up after execution? 

<img width="794" alt="screen shot 2018-08-27 at 7 35 31 pm" src="https://user-images.githubusercontent.com/26976153/44657756-97660d80-aa30-11e8-9538-793500b7912d.png">

```
currently using 
"react-native-payments": "^0.7.0",
"react-native" "^0.56",
and I have updated the **play-services-wallet:16.0.0**
 implementation 'com.google.android.gms:play-services-wallet:16.0.0'
```

Thanks in advance

**Comment by eMatsiyana** [comment]
Same issue I have. 
Using an emulator: Samsung Galaxy S3 - 4.3 API 18

Nothing comes up when I invoke paymentRequest.show().

**Comment by SimoneLSK** [comment]
@eMatsiyana may I know if it is emulator problem?

**Comment by prasadrenukdas** [comment]
@SimoneLSK I faced this issue on both emulator and device. Tested on google pixel 2 (Android 8)

**Comment by imadarif** [comment]
Payment sheet is not showing

**Comment by yosephha** [comment]
+1
