### ISSUE TITLE
Meeting Apple Store compliance

### ISSUE THREAD

**Issue by tmaly1980** [naoufal/react-native-payments#12]
My understanding is Apple requires an in-app purchase option for any payments done through mobile apps. They want their 30% cut. Does using this library with Apply Pay work to comply with their requirements? I'm new to mobile payment processing and trying to understand how to offer payment/subscription systems in a RN app that meets Apple's guidelines. Do you have pointers to documentation perhaps?

**Comment by naoufal** [comment]
Sure, check out the **Apple Pay or In-App Purchase** section of this page. 
https://developer.apple.com/apple-pay/get-started/
