### ISSUE TITLE
Module ReactNativePayments requires main queue setup

### ISSUE THREAD

**Issue by lautapercuspain** [naoufal/react-native-payments#127]
I'm getting this warning, after install and setup, any guidelines ?
<img width="319" alt="captura de pantalla 2018-11-01 a la s 3 17 21 p m" src="https://user-images.githubusercontent.com/622564/47883281-c2caf700-dde9-11e8-80a0-76b25fb2b82f.png">

**Comment by zibs** [comment]
I made a pr at #129 to fix this

**Comment by lautapercuspain** [comment]
Cool. Seems to be ok!
Thank you!

**Comment by Andreyco** [comment]
resolved in #129, version 0.7.1 released
