### ISSUE TITLE
Apple Pay - Trial Period Support

### ISSUE THREAD

**Issue by VietChaien** [naoufal/react-native-payments#131]
Hi all,
I'm using braintree addon to integrate Apple Pay,
My problem is: How to user can use ApplePay to buy trial period and user's account will be reduce after trial period end.
I follow this case  #29  but it can't create trial period.
Please tell me know what i have to do ?
Thank you

**Comment by Andreyco** [comment]
Hey there.
I have zero experience with Braintree trials but I suppose you charge your customer as per usual.
Braintree allows you to delay first charge until after trial period end. More on this topic here https://articles.braintreepayments.com/guides/recurring-billing/trial-periods
