### ISSUE TITLE
How can i just use Braintree in react-native

### ISSUE THREAD

**Issue by rajnishraj** [naoufal/react-native-payments#145]
Hello,

I just want to use braintree and not Apple/Google Pay.. is it possible? If yes, then what will be configuration?

Thanks for support.

**Comment by Andreyco** [comment]
Yup, it is possible. You can find all the info you need here:
iOS - https://developers.braintreepayments.com/start/hello-client/ios/v4
Android - https://developers.braintreepayments.com/start/hello-client/android/v2
