### ISSUE TITLE
Support for Authorize.net payment gateway

### ISSUE THREAD

**Issue by cjadhav** [naoufal/react-native-payments#15]
Hi @naoufal,

Thanks a lot for building this awesome module.
I would like to know your plan to release the [Authorize.net](https://www.authorize.net/) payment gateway.

Thanks a lot again.

**Comment by naoufal** [comment]
I don't have plans to integrate Authorize.net at moment.

I'm to happy to point you in the right direction if you wanted to contribute it as an add-on though.

**Comment by peterpme** [comment]
Hey @cjadhav!!

I need support for Authorize.net too! Let me know when its complete. Thanks!!

**Comment by tonycoco** [comment]
@naoufal I was looking to build the Authorize.net add-on. Can you point me to the right direction?
