### ISSUE TITLE
PKPaymentButton was not found in UIManager

### ISSUE THREAD

**Issue by famu1hundred** [naoufal/react-native-payments#155]
I'm getting the error:

`Invariant Violation: requireNativeComponent: 'PKPaymentButton' was not found in UIManager`

I am using iOS 12.1.2
I ran the following:

`npm install react-native-payments`
`react-native link react-native-payments`
`pod install`

`import { ApplePayButton } from "react-native-payments";`
`<ApplePayButton type="plain" style="whiteOutline" onPress={()=>{}}/>`

I also tried linking the` libReactNativePayments.a` file in the `Link Binary with Libraries` but still I see the issue.

**Comment by Andreyco** [comment]
sorry, this should definitely work. Clean npm install?

**Comment by famu1hundred** [comment]
If by clean you mean to remove `node_modules` folder and try again, I’ve certainly tried that as well. In order to get the pod to install I had to do the following. 

Here are the steps I took:

`rm -rf node_modules`
`yarn install react-native-payments`
`react-native link react-native-payments`

changed 2 lines in ReactNativePayments.podspec (pod install would not complete without this change)

`s.source_files  = 'lib/ios/*.{h,m}'` and
`s.dependency 'React'`
`pod install`

this produced the UIManager error. Please help. My project really needs this package in order to accept Apple Pay.

**Comment by sgehly** [comment]
I ran into this issue when not including the .xcodeproj inside my libraries & manually linking the library. It seems like it's another one of those issues with `react-native link` failing

**Comment by famu1hundred** [comment]
@sgehly Do you mind mapping out the steps? I tried manual linking as well and still had the same error

**Comment by sgehly** [comment]
@famu1hundred - Try this fork:
`"react-native-payments": "github:cumom/react-native-payments"`

I just dragged the .xcodeproj from `node_modules/react-native-payments/lib/ios` into the libraries folder & linked the build product in the target

**Comment by famu1hundred** [comment]
This still does not work...I feel like I have tried everything. I'm still getting the same issue whether I manually link or try `react-native link` or BOTH. @sgehly I also tried your fork and still the same problem. I added the `.xcodeproj` to the Libraries folder and added the `libReactNativePayments.a` to the build product in the target.
Nothing seems to work....

**Comment by famu1hundred** [comment]
Decided to use `expo-payments-stripe` instead. Much easier
https://docs.expo.io/versions/v32.0.0/sdk/payments/#openapplepaysetupasync

**Comment by famu1hundred** [comment]
I was able to resolve this by manually linking...turns out I had the directories wrong in the Header Search paths.

**Comment by Andreyco** [comment]
Is this something that our linking process does incorrectly? If so, could you post details?

**Comment by abdullah-shiwani** [comment]
> Is this something that our linking process does incorrectly? If so, could you post details?

I need to make below changes in `react-native-payments/ReactNativePayments.podspec` file to get things work:

- `s.source_files = 'lib/ios/*.{h,m}` -> `s.source_files = 'lib/ios/**/*.{h,m}`
[Here](https://github.com/naoufal/react-native-payments/pull/160/commits/e58135e64491d3e53e2c04b6fba84ba0acef23e7#diff-daa2ec561316c218e7b8910b1344511cL19) is the link of PR of someone.

- Add the line before `end`
  `s.dependency "React"`

- `s.homepage = giturl` -> `s.homepage     = 'giturl'`

Screenshot of final codebase attached for the reference
![Uploading image.png…]()

**Comment by tvelev92** [comment]
for me `s.source_files  = "**/*.{h,m}"` in the podspec solved the issue but im running a react-native plugin in a cordova app. Basically pod install was not pulling anything from the View directory in lib/ios at all

**Comment by Tanzeel-ur-rehman-git** [comment]
On IOS it is working fine but on android, it shows error PKPaymentButton was not found in UIManager, anyone know how to fix that problem on android ?
