### ISSUE TITLE
Can not find show();

### ISSUE THREAD

**Issue by liyukeGit** [naoufal/react-native-payments#16]
I completed the first three steps：
Registering as a Merchant
Importing the Library
Initializing the Payment Request

paymentRequest.show();Can not find it
![wx20170811-181403](https://user-images.githubusercontent.com/22114385/29209423-fce94a24-7ec0-11e7-92f7-cae425d09080.png)

**Comment by naoufal** [comment]
@liyukeGit Can you post a stack trace.

**Comment by naoufal** [comment]
Just tested this on the latest release and it works.

**Comment by SimoneLSK** [comment]
@liyukeGit , 

Hello, may I know how you fixed this issue? 
there is not payment sheet show after I clicked **paymentRequest.show()**

**Comment by hiren0412** [comment]
Same issue face in Android.
