### ISSUE TITLE
ReactNativePayments pod failed - iOS

### ISSUE THREAD

**Issue by jeevankumarkanuganti** [naoufal/react-native-payments#164]
The ReactNativePayments pod failed to validate due to 1 error:
- ERROR | [iOS] attributes: Unacceptable type Hash for homepage. Allowed values: [String].

**Comment by yatishAgrawal** [comment]
I solved this issue by changing into the ReactNativePayments.podspec file:

s.homepage     = giturl  =>  s.homepage     = "giturl"

**Comment by jeevankumarkanuganti** [comment]
@yatishAgrawal  - 

it works . Thanks a lot

**Comment by jitendravarma** [comment]
Where is it located?

**Comment by valeriik** [comment]
Maybe right solution is described in separate issue here:
https://github.com/naoufal/react-native-payments/issues/163#issuecomment-564967141

But anyway, guys, so when the fix will be applied for this library?
