### ISSUE TITLE
Error with apple pay in IOS simulator

### ISSUE THREAD

**Issue by Alekseyideas** [naoufal/react-native-payments#169]
After updating Xcode to 10.3 apple pay with Stripe stoped working on ios simulator, on real device all work fine. 
Error in console: https://prnt.sc/oq3vnd
Can somebody help me with this error? Thanks

**Comment by wkoutre** [comment]
+1 to this, using Braintree though.

XCode 10.3
iOS simulator no longer works
Physical device works

Same error as in screenshot shared by @Alekseyideas , happening upon tap of `Pay with Passcode`

**Comment by wkoutre** [comment]
@Alekseyideas  Ah, this one was simple: The problematic simulator was running iOS 12.4.

12.2 and 12.3 both work as expected. This can probably be closed.
