### ISSUE TITLE
BUG/Error install library for rn>60

### ISSUE THREAD

**Issue by alexeyz-PE** [naoufal/react-native-payments#184]
### ReactNativePayments.podspec

```
package = JSON.parse(File.read(File.join(__dir__, "package.json")))
version = package["version"]
giturl = package["repository"]

Pod::Spec.new do |s|
  s.name         = "ReactNativePayments"
  s.version      = package["version"]
  s.summary      = "react-native-payments"
  s.description  = <<-DESC
                  Native Payments (Google and Apple Pay) from React-Native
                   DESC
  s.homepage     = "giturl"
  s.license      = "MIT"
  s.authors      = "Naoufal Kadhom", "Andrej Badin"
  s.platform     = :ios, '10.0'
  s.source       = { :git => "https://github.com/naoufal/react-native-payments.git", :tag => "#{s.version}" }
  s.source_files  = 'packages/react-native-payments/lib/ios/*.{h,m}'
  s.requires_arc = true

end
```

### Console error
```
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "ReactNativePayments":
  In Podfile:
    ReactNativePayments (from `../node_modules/react-native-payments`)

Specs satisfying the `ReactNativePayments (from `../node_modules/react-native-payments`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by Piotrovskyi** [comment]
@alexeyz-PE  How have you managed this? I have faced the same issue

**Comment by Natkarock** [comment]
> @alexeyz-PE How have you managed this? I have faced the same issue

I have the same issue. did you solved it?

**Comment by Natkarock** [comment]
> ### ReactNativePayments.podspec
> ```
> package = JSON.parse(File.read(File.join(__dir__, "package.json")))
> version = package["version"]
> giturl = package["repository"]
> 
> Pod::Spec.new do |s|
>   s.name         = "ReactNativePayments"
>   s.version      = package["version"]
>   s.summary      = "react-native-payments"
>   s.description  = <<-DESC
>                   Native Payments (Google and Apple Pay) from React-Native
>                    DESC
>   s.homepage     = "giturl"
>   s.license      = "MIT"
>   s.authors      = "Naoufal Kadhom", "Andrej Badin"
>   s.platform     = :ios, '10.0'
>   s.source       = { :git => "https://github.com/naoufal/react-native-payments.git", :tag => "#{s.version}" }
>   s.source_files  = 'packages/react-native-payments/lib/ios/*.{h,m}'
>   s.requires_arc = true
> 
> end
> ```
> 
> ### Console error
> ```
> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> [!] CocoaPods could not find compatible versions for pod "ReactNativePayments":
>   In Podfile:
>     ReactNativePayments (from `../node_modules/react-native-payments`)
> 
> Specs satisfying the `ReactNativePayments (from `../node_modules/react-native-payments`)` dependency were found, but they required a higher minimum deployment target.
> ```
I have the same issue. did you solved it?

**Comment by abhilash-linkites** [comment]
I resolve it by below changes
1. open this file ReactNativePayments.podspec and paste below code
2. change s.platform according to your Deployment target
3. In terminal Go to ios folder and run following command pod cache clean --all && pod install

Code:

require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))
version = package["version"]
giturl = package["repository"]["url"]

Pod::Spec.new do |s|
  s.name         = "ReactNativePayments"
  s.version      = package["version"]
  s.summary      = "react-native-payments"
  s.description  = <<-DESC
                  Native Payments (Google and Apple Pay) from React-Native
                   DESC
  s.homepage = "giturl"
  s.license      = "MIT"
  s.authors      = "Naoufal Kadhom", "Andrej Badin"
  s.platform     = :ios, '9.0'
  s.source       = { :git => "https://github.com/naoufal/react-native-payments.git", :tag => "#{s.version}" }
  s.source_files  = "lib/ios/*.{h,m}"
  s.requires_arc = true
  s.dependency "React"

end

**Comment by abhiilash** [comment]
I resolve it by below changes

1. open this file ReactNativePayments.podspec and paste below code
2. change s.platform according to your Deployment target
3. In terminal Go to ios folder and run following command pod cache clean --all && pod install

Code:

require "json"

package = JSON.parse(File.read(File.join(dir, "package.json")))
version = package["version"]
giturl = package["repository"]["url"]

Pod::Spec.new do |s|
s.name = "ReactNativePayments"
s.version = package["version"]
s.summary = "react-native-payments"
s.description = <<-DESC
Native Payments (Google and Apple Pay) from React-Native
DESC
s.homepage = "giturl"
s.license = "MIT"
s.authors = "Naoufal Kadhom", "Andrej Badin"
s.platform = :ios, '9.0'
s.source = { :git => "https://github.com/naoufal/react-native-payments.git", :tag => "#{s.version}" }
s.source_files = "lib/ios/*.{h,m}"
s.requires_arc = true
s.dependency "React"

end

**Comment by aspidvip** [comment]
this is work code:
`
require "json"

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
version = package["version"]
giturl = package["repository"]["url"]

Pod::Spec.new do |s|
s.name = "ReactNativePayments"
s.version = package["version"]
s.summary = "react-native-payments"
s.description = <<-DESC
Native Payments (Google and Apple Pay) from React-Native
DESC
s.homepage = "giturl"
s.license = "MIT"
s.authors = "Naoufal Kadhom", "Andrej Badin"
s.platform = :ios, '9.0'
s.source = { :git => "https://github.com/naoufal/react-native-payments.git", :tag => "#{s.version}" }
s.source_files = "lib/ios/*.{h,m}"
s.requires_arc = true
s.dependency "React"
end
`

**Comment by CezarCobuz** [comment]
> this is work code:
> 
> > require "json"
> > package = JSON.parse(File.read(File.join(`__dir__`, 'package.json')))
> > version = package["version"]
> > giturl = package["repository"]["url"]
> > Pod::Spec.new do |s|
> > s.name = "ReactNativePayments"
> > s.version = package["version"]
> > s.summary = "react-native-payments"
> > s.description = <<-DESC
> > Native Payments (Google and Apple Pay) from React-Native
> > DESC
> > s.homepage = "giturl"
> > s.license = "MIT"
> > s.authors = "Naoufal Kadhom", "Andrej Badin"
> > s.platform = :ios, '9.0'
> > s.source = { :git => "https://github.com/naoufal/react-native-payments.git", :tag => "#{s.version}" }
> > s.source_files = "lib/ios/*.{h,m}"
> > s.requires_arc = true
> > s.dependency "React"
> > end

Tried this but I get:

>  Invalid `Podfile` file: No such file or directory @ rb_sysopen
 #  -------------------------------------------
 #  
 >  package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
 #  version = package["version"]
 #  -------------------------------------------

**Comment by vmajsuk** [comment]
Actually, you should not change ReactNativePayments.podspec
Instead, change the deployment target in xcode, and don't forget to update podfile: https://stackoverflow.com/a/40705146
