### ISSUE TITLE
TypeError: null is not an object (evaluating 'ReactNativePayments.show')]

### ISSUE THREAD

**Issue by Willianwg** [naoufal/react-native-payments#197]
I'm using android, and every time i try to call the function that happens.. any solution?

**Comment by daxaxelrod** [comment]
Seems like it drills down to the call on NativePayments.js:84

show(methodData, details, options = {}) {
    return new Promise((resolve, reject) => {
      if (IS_ANDROID) { 
        ReactNativePayments.show( <- **undefined after importing from  NativeModules**
          methodData,
          details,
          options,
          (err) => reject(err),
          (...args) => { console.log(args); resolve(true) }
        );

        return;
      }

**Comment by daxaxelrod** [comment]
Sure enough, its my own fault. In build.grade, there was no reference to ReactNativePayments anywhere, weird for a linked package. I could have swore I linked the package during installation but might have just forgotten honestly ¯\_(ツ)_/¯

anyways just try reruning 
```react-native link react-native-payments```
and check your MainApplication.java to see if new ReactNativePaymentsPackage() is in your package list

**Comment by ramisalem** [comment]
@daxaxelrod  Should I run link command even in react-native 0.62.2 ?

**Comment by daxaxelrod** [comment]
Nah I wouldnt, probably not best practice. Try uninstalling and reinstalling the package. After that, check your settings.gradle, your android/app/buid.gradle and your MainActivity.java. They should all have references to the ":react-native-payments" sub project.

**Comment by ramisalem** [comment]
@daxaxelrod  Thanks it works I used @naoufal fork, I am facing another issue with Abort error in real  IOS device nut works in ios simulators

**Comment by daxaxelrod** [comment]
Can you close this issue, open a new one and tag me? Makes it easier for people to find when searching for similar issues in the future :D

**Comment by Renjithcse** [comment]
I am also facing this issue in IOS devices

**Comment by yahm23** [comment]
> Seems like it drills down to the call on NativePayments.js:84
> 
> ```
> show(methodData, details, options = {}) {
>     return new Promise((resolve, reject) => {
>       if (IS_ANDROID) { 
>         ReactNativePayments.show( <- **undefined after importing from  NativeModules**
>           methodData,
>           details,
>           options,
>           (err) => reject(err),
>           (...args) => { console.log(args); resolve(true) }
>         );
> 
>         return;
>       }
> ```

What are you doing here, out of interest? I'm getting the same error as OP, and have tried re-installing package as well as 'manually' linking through terminal. Any help greatly appreciated.

**Comment by TejasGhanwat** [comment]
I'm getting similar error with package called 'react-native-palette' 

Error: TypeError: null is not an object (evaluating 'RNPalette.getNamedSwatches')

 const imageUri = navigation.getParam('photo')
 calculateSome =()=> {
   console.log("im entering the function")
   if(Platform.OS==='android'){
    getNamedSwatches(imageUri, (error, swatches) => {
      if (error) {
        console.log(error);
      } else {
        swatches.sort((a, b) => {
          return b.population - a.population;
        });
        swatches.forEach((swatch) => {
          console.log(swatch.swatchInfo);
        });
      }
    });
   }
  }

**Comment by nabilfreeman** [comment]
Hey all, autolinking is now supported on version 0.8 up! Hopefully bug is squashed forever. Closing this issue.

Tejas sorry, your issue could be anything as it's a different library. Better to ask on their repo.

**Comment by keving-vargasb** [comment]
https://developers.google.com/pay/api/android/guides/setup

in your android/build.gradle 

dependencies {
...
classpath 'com.google.android.gms:play-services-wallet:18.1.2'
classpath 'com.android.support:appcompat-v7:24.1.1'
}
