### ISSUE TITLE
Crashing on method show

### ISSUE THREAD

**Issue by ButuzGOL** [naoufal/react-native-payments#211]
Trying to test on simulator
Using this code/tutorial https://enappd.com/blog/implement-apple-pay-in-react-native-apps/93/
paymentRequest.canMakePayments() works fine
but when show() it crashing ?

**Comment by ButuzGOL** [comment]
Issue was because landscape mode

**Comment by toplongguodev** [comment]
hi, did you implement google pay for android?
I am working on it and paymentRequest.show() keeps throwing me error.

**Comment by Surik266** [comment]
Same on my side app crashing after paymentRequest.show(). any ideas on how to fix this?
