### ISSUE TITLE
Crashing in landscape mode

### ISSUE THREAD

**Issue by ButuzGOL** [naoufal/react-native-payments#214]
```
*** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [PKPaymentAuthorizationViewController shouldAutorotate] is returning YES'
```

**Comment by nabilfreeman** [comment]
It's been a while, but there's nothing we can do about this - it's a native exception from Apple due to portrait being disabled in your project's build settings.

For Face ID the device has to be in portrait.

I'll close this - good luck!
