### ISSUE TITLE
Installation fails with "..required a higher minimum deployment target"

### ISSUE THREAD

**Issue by alex-mironov** [naoufal/react-native-payments#215]
On an attempt to install the module 
```
yarn add react-native-payments
cd ios && pod install
```
I get an error

```
[!] CocoaPods could not find compatible versions for pod "ReactNativePayments":
  In Podfile:
    ReactNativePayments (from `../node_modules/react-native-payments`)

Specs satisfying the `ReactNativePayments (from `../node_modules/react-native-payments`)` dependency were found, but they required a higher minimum deployment target.
exit 1
```
What should be the minimum deployment target? I use iOS 9.0

My dependencies
```
    "react-native": "0.61.3",
    "react-native-payments": "^0.7.1",
```

**Comment by ButuzGOL** [comment]
use this advice 
https://github.com/naoufal/react-native-payments/issues/166#issuecomment-525264803
and put in your podfile
platform :ios, '10.0'

**Comment by Quentinb** [comment]
After upgrading to the latest versions of react and react-native, the above solution solved the issue...

```
"react": "17.0.2",
"react-native": "0.65.1",
```

**Comment by ROSHANSEBASTIAN** [comment]
If you have expo modules in your app, run expo doctor and then you will find the apt version of library
