### ISSUE TITLE
How to update Apple Pay to version 5

### ISSUE THREAD

**Issue by iamacoderguy** [naoufal/react-native-payments#227]
Hi all,

In our app, we will support the payment network "mada" which has been supported by Apple Pay since version 5 (https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentrequest/1916122-supportednetworks).

I'm not sure which version of Apple Pay react-native-payments is supporting, but it's not 5. The app crashes when I added "mada" as a supported network.

Does anyone know how to update the Apple Pay SDK in react-native-payments?

**Comment by SerhiiMeketiuk** [comment]
Hi @iamacoderguy. 

Add this part 
```
if (iOSVersion >= 12.1) {
        [supportedNetworksMapping setObject:PKPaymentNetworkMada forKey:@"mada"];
}
```
to `getSupportedNetworksFromMethodData` method in file `/node_modules/react-native-payments/lib/iOS/ReactNativePayments.m` 

It will help with crashes.

**Comment by iamacoderguy** [comment]
> Hi @iamacoderguy.
> 
> Add this part
> 
> ```
> if (iOSVersion >= 12.1) {
>         [supportedNetworksMapping setObject:PKPaymentNetworkMada forKey:@"mada"];
> }
> ```
> 
> to `getSupportedNetworksFromMethodData` method in file `/node_modules/react-native-payments/lib/iOS/ReactNativePayments.m`
> 
> It will help with crashes.

It works like a charm.
Thank you,
