### ISSUE TITLE
Dose it supporty Payfort payment gateway? 

### ISSUE THREAD

**Issue by ramisalem** [naoufal/react-native-payments#247]

**Comment by nabilfreeman** [comment]
Hey @ramisalem, it doesn't but I'm happy to assist somebody in implementing this.

I would need you or someone else to take the lead on it.

**Comment by akinlekan28** [comment]
@nabilfreeman  @ramisalem it supports payfort. Everything needed by parfort endpoint is contained in the payment response generated.

**Comment by ramisalem** [comment]
@akinlekan28  paymentMethod filed is missing which is required by Payfort endpoint 

 // paymentMethod example 
{ 
"paymentMethod": { "network": "MasterCard", "type": "credit", "displayName": "MasterCard 4248"

}

**Comment by ramisalem** [comment]
@nabilfreeman Sure, I would love to contribute

**Comment by akinlekan28** [comment]
@ramisalem this is the raw apple token generated and that is all you need to send to payfort

`'_requestId' => 'Sahlh App Checkout',
  '_methodName' => 'apple-pay',
  '_details' => 
  array (
    'paymentData' => 
    array (
      'version' => 'EC_v1',
      'data' => '3Oruoak6ql+jh0A4J+Y4INR+14jve67i2rK3C8Hg3R45pNuTYQFUu0BANcfLnoEnSEigrOLW1WM/NJJjEkGQ5VrzpEPxvkbi1GbGN65+wCfRCycVKuM8d5VxY56d1woZcreXxcfkeOkA5e+INdR6Q9eZnPkmInEtWcvHwdG3TcSYNLYFEPc8+6BIbOwTA5PayNhUh/mlvChWqbuBTkYib64WXeLznDBhg+E7T5cND1JN7RxNB2N5PF1spy9QVABOWxO8SLnloaZzZMa71mAuHLEztqtJSnRwkkX9FP193ZhjHFqlo+yNP+KNcKgVwWpqWMEjw59ii6g2n7Z9OsdpiNPYCa5TMWIko9dIGuvuicHPJErC3QwEBo53qs6wNgXEZr7LVomggq4uvMWFLuliLI44Vi4zUic9iE14utNGCA==',
      'signature' => 'MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwEAAKCAMIID4zCCA4igAwIBAgIITDBBSVGdVDYwCgYIKoZIzj0EAwIwejEuMCwGA1UEAwwlQXBwbGUgQXBwbGljYXRpb24gSW50ZWdyYXRpb24gQ0EgLSBHMzEmMCQGA1UECwwdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMB4XDTE5MDUxODAxMzI1N1oXDTI0MDUxNjAxMzI1N1owXzElMCMGA1UEAwwcZWNjLXNtcC1icm9rZXItc2lnbl9VQzQtUFJPRDEUMBIGA1UECwwLaU9TIFN5c3RlbXMxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwhV37evWx7Ihj2jdcJChIY3HsL1vLCg9hGCV2Ur0pUEbg0IO2BHzQH6DMx8cVMP36zIg1rrV1O/0komJPnwPE6OCAhEwggINMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUI/JJxE+T5O8n5sT2KGw/orv9LkswRQYIKwYBBQUHAQEEOTA3MDUGCCsGAQUFBzABhilodHRwOi8vb2NzcC5hcHBsZS5jb20vb2NzcDA0LWFwcGxlYWljYTMwMjCCAR0GA1UdIASCARQwggEQMIIBDAYJKoZIhvdjZAUBMIH+MIHDBggrBgEFBQcCAjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMDYGCCsGAQUFBwIBFipodHRwOi8vd3d3LmFwcGxlLmNvbS9jZXJ0aWZpY2F0ZWF1dGhvcml0eS8wNAYDVR0fBC0wKzApoCegJYYjaHR0cDovL2NybC5hcHBsZS5jb20vYXBwbGVhaWNhMy5jcmwwHQYDVR0OBBYEFJRX22/VdIGGiYl2L35XhQfnm1gkMA4GA1UdDwEB/wQEAwIHgDAPBgkqhkiG92NkBh0EAgUAMAoGCCqGSM49BAMCA0kAMEYCIQC+CVcf5x4ec1tV5a+stMcv60RfMBhSIsclEAK2Hr1vVQIhANGLNQpd1t1usXRgNbEess6Hz6Pmr2y9g4CJDcgs3apjMIIC7jCCAnWgAwIBAgIISW0vvzqY2pcwCgYIKoZIzj0EAwIwZzEbMBkGA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTQwNTA2MjM0NjMwWhcNMjkwNTA2MjM0NjMwWjB6MS4wLAYDVQQDDCVBcHBsZSBBcHBsaWNhdGlvbiBJbnRlZ3JhdGlvbiBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATwFxGEGddkhdUaXiWBB3bogKLv3nuuTeCN/EuT4TNW1WZbNa4i0Jd2DSJOe7oI/XYXzojLdrtmcL7I6CmE/1RFo4H3MIH0MEYGCCsGAQUFBwEBBDowODA2BggrBgEFBQcwAYYqaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwNC1hcHBsZXJvb3RjYWczMB0GA1UdDgQWBBQj8knET5Pk7yfmxPYobD+iu/0uSzAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFLuw3qFYM4iapIqZ3r6966/ayySrMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuYXBwbGUuY29tL2FwcGxlcm9vdGNhZzMuY3JsMA4GA1UdDwEB/wQEAwIBBjAQBgoqhkiG92NkBgIOBAIFADAKBggqhkjOPQQDAgNnADBkAjA6z3KDURaZsYb7NcNWymK/9Bft2Q91TaKOvvGcgV5Ct4n4mPebWZ+Y1UENj53pwv4CMDIt1UQhsKMFd2xd8zg7kGf9F3wsIW2WT8ZyaYISb1T4en0bmcubCYkhYQaZDwmSHQAAMYIBjTCCAYkCAQEwgYYwejEuMCwGA1UEAwwlQXBwbGUgQXBwbGljYXRpb24gSW50ZWdyYXRpb24gQ0EgLSBHMzEmMCQGA1UECwwdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTAghMMEFJUZ1UNjANBglghkgBZQMEAgEFAKCBlTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yMTAyMTgwODUyMzFaMCoGCSqGSIb3DQEJNDEdMBswDQYJYIZIAWUDBAIBBQChCgYIKoZIzj0EAwIwLwYJKoZIhvcNAQkEMSIEIIusXjZ6cwJPAor2TZsbOnbeuFq4+MAWTdDy7zTKjIe/MAoGCCqGSM49BAMCBEgwRgIhAKRX7KY5sViWYLJ/kkEIzo1kv0LLMBFRJBLMOaOCE+SPAiEAlmYws5kZRNOx9vvwL1GAzUA65rf0P2LMIjaZ+nUxga0AAAAAAAA=',
      'header' => 
      array (
        'ephemeralPublicKey' => 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvJAolRxyKTbTLb7TXFuwqQ8/vN5N93+BdEUHalxU0Xr3vsE8Dv9VzbbA9G0Yqc4shNJAgLmyL2VlTU0G1GSWWw==',
        'publicKeyHash' => 'w4cT5J5bYI36glyBSAjwitysn9lQh7SSGurGchpEcN8=',
        'transactionId' => '3ef75295f8f1f406ca96b19216db4ee7aecccef6d7fe571a5d6a4a3275b892f9',
      ),
    ),
    'billingContact' => NULL,
    'shippingContact' => NULL,
    'transactionIdentifier' => '3EF75295F8F1F406CA96B19216DB4EE7AECCCEF6D7FE571A5D6A4A3275B892F9',
    'paymentMethod' => 
    array (
      'network' => 'Visa',
      'type' => 'PKPaymentMethodTypeDebit',
      'displayName' => 'Visa 3864',
    ),
  ),
  '_shippingAddress' => NULL,
  '_shippingOption' => NULL,
  '_payerName' => NULL,
  '_payerPhone' => NULL,
  '_payerEmail' => NULL,
  '_completeCalled' => false`

**Comment by ramisalem** [comment]
@akinlekan28  Hi, Yes that is right, Thank you very much

**Comment by nabilfreeman** [comment]
Great! Glad this is solved. Just to check, was the raw token returned correctly from the `paymentRequest`?

**Comment by akinlekan28** [comment]
@nabilfreeman Yes, the token was returned correctly.
