### ISSUE TITLE
Stripe payment not charging, but it succeeds

### ISSUE THREAD

**Issue by nica0012** [naoufal/react-native-payments#267]
For some reason I am not receiving payments on stripe. They are succeeding but the problem is a charge not being created?

Is anyone else experiencing this? is not, how do i ensure my users are being charged?

**Comment by nabilfreeman** [comment]
Hey Hugo, that's by design - you need to send the encrypted card token to your server and process the payment remotely. Let me know if you have any more questions and I can try to help 😁

**Comment by nica0012** [comment]
Hey @nabilfreeman thanks for getting back to me so fast. Good to know - would the server in my case be Stripe? I figured that was the point of using a third party API? I can see the payments coming through in the developer logs, is there some sort of configuration I need to do on stripe to accept these payments? Thanks!

**Comment by nica0012** [comment]
Great, I've figured it out - cheers!

**Comment by nabilfreeman** [comment]
Amazing @nica0012 ! To help other people coming here later would you mind telling your solution?

**Comment by nica0012** [comment]
In my case I'm using firebase, so I used firebase cloud functions to send the response with the token to their server (cloud functions) to complete the payment there 👌🏼
