### ISSUE TITLE
Several links broken in the docs

### ISSUE THREAD

**Issue by rakeshpetit** [naoufal/react-native-payments#274]
Thank you for this awesome library.
Under the API section at the bottom of the README, multiple links are broken. I get an error 404 and redirected to the wrong URL. An example is [NativePayments](https://github.com/naoufal/react-native-payments/blob/master/packages/react-native-payments/docs/NativePayments.md)

The links that are broken are: 
- NativePayments
- PaymentRequest
- PaymentRequestUpdateEvent
- PaymentResponse

I can fix these and create a PR if required.

**Comment by nabilfreeman** [comment]
Closed by #275 👏
