### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): 10

### ISSUE THREAD

**Issue by whysetiawan** [naoufal/react-native-payments#28]
Hello guys, i am newbie in react native. Then i'm learning about this library. I just try to show react-native-android payments. But when i click the button i got an error .

> Possible Unhandled Promise Rejection (id: 0): 10

```
    androidPay(){
    	const DETAILS = {
			  id: 'basic-example',
			  displayItems: [
			    {
			      label: 'Movie Ticket',
			      amount: { currency: 'USD', value: '15.00' }
			    }
			  ],
			  total: {
			    label: 'Merchant Name',
			    amount: { currency: 'USD', value: '15.00' }
			  }
			};
    	const METHOD_DATA = [{
			  supportedMethods: ['android-pay'],
			  data: {
			    supportedNetworks: ['visa', 'mastercard', 'amex'],
			    currencyCode: 'USD',
			    environment: 'TEST', // defaults to production
			    paymentMethodTokenizationParameters: {
			      tokenizationType: 'NETWORK_TOKEN',
			      parameters: {
			        publicKey: 'pk_test_jTdyDhKRi0XUBF12a3mALc4n'
			      }
			    }
			  }
			}];
			const paymentRequest = new PaymentRequest(METHOD_DATA, DETAILS)
			paymentRequest.show().then((response) => {
    		console.log(response)
    	})

    }
```

**Comment by Andreyco** [comment]
What iOS version are you running? It's possibly related to #31

**Comment by campierce88** [comment]
I am also encountering this issue for android only. iOS works no problem.

**Comment by whysetiawan** [comment]
i'm using android pay sir

**Comment by EpicNem** [comment]
Hi, have the same error

**Comment by tsubery** [comment]
Hi, I encountered the same error. Fixed the unhandled rejection [here](https://github.com/tsubery/react-native-payments/commit/5599635bff6df0a5a4b33317ab46a64d0670bd7c). I'd open a pull request but don't want to create diff conflicts with other pull requests.
This fix didn't help me find out the cause of the "10" error code. I used logcat and saw a detailed error message from the package WalletMerchantError. In my case it was complaying about the invalid publicKey. Hope this information helps :)

**Comment by jthink0228** [comment]
excuse me, where to find the publicKey?
i have no idea...

many thanks

**Comment by Amnesthesia** [comment]
I'm getting this too, using the publicKey provided by Braintree — perhaps that's not the one I'm supposed to be using?

**Comment by Amnesthesia** [comment]
Okay, it works if you set your `gateway` parameter correctly, and set the publicKey to your public key from e.g braintree, and also set `GATEWAY_TOKEN` (instead of `NETWORK_TOKEN` as the documentation shows). Now i get another unhandled promise rejection, but it's some progress at least

Documentation shows:

```json
{
      supportedMethods: ['android-pay'],
      data: {
        supportedNetworks: ['visa', 'mastercard', 'amex'],
        currencyCode: 'USD',
        environment: 'TEST', // defaults to production
        paymentMethodTokenizationParameters: {
          tokenizationType: 'NETWORK_TOKEN',
          parameters: {
            publicKey: 'YOUR KEY HERE',
          },
        },
      },
    },
```

What got me a bit further:

```json
{
      supportedMethods: ['android-pay'],
      data: {
        supportedNetworks: ['visa', 'mastercard', 'amex'],
        currencyCode: 'USD',
        environment: 'TEST', // defaults to production
        paymentMethodTokenizationParameters: {
          tokenizationType: 'GATEWAY_TOKEN',
          parameters: {
            gateway: 'braintree',
            publicKey: 'PUBLIC KEY FROM BRAINTREE',
          },
        },
      },
    },
```

**Comment by Andreyco** [comment]
Could you post more info on rejection?

**Comment by Amnesthesia** [comment]
I think I solved it by finding the correct public key somewhere in the Play Console (if I remember correctly), but ended up having to scrap it all anyway because Google Play isn't available in my country :(

**Comment by Andreyco** [comment]
What a pity :-/

**Comment by Hemanth1985** [comment]
Where should we find the public key?

**Comment by mam17** [comment]
Same problem here, I give up.... by the way, you can get publicKey from here https://payments.developers.google.com/paymentmethodtoken/test/keys.json

**Comment by b3hz4d** [comment]
I had this issue too.
It's because your linking with react native having problem, check your MainApplication.java and be sure that react native payments included

**Comment by tomaszNowakKivy** [comment]
For me, it works only with "GATEWAY_TOKEN" type and "braintree" or "stripe" gateway. Is it really necessary to use one of them?

**Comment by Wilson-Lim** [comment]
I am still getting the same issue, any fix ?

**Comment by TonchoLozev** [comment]
Follow the steps at secant: **Use OpenSSL to generate a public key**(https://developers.google.com/pay/api/android/guides/resources/payment-data-cryptography#using-openssl) 
And then use the public key.
