### ISSUE TITLE
[iOS] paymentToken not present on real device

### ISSUE THREAD

**Issue by Andreyco** [naoufal/react-native-payments#30]
Yesterdays production deployment kinda surprised me. 

When testing in sandbox/production on device, `paymentToken` got lost. On simulator, it works perfectly.

Despite token arrives into JS ["accept" handler ](https://github.com/naoufal/react-native-payments/blob/master/packages/react-native-payments/lib/ios/ReactNativePayments.m#L323), it does pass [`_getPlatformDetailsIOS`](https://github.com/naoufal/react-native-payments/blob/5b45f79452009f7f48a6d3e762db885f47d67357/packages/react-native-payments/lib/js/PaymentRequest.js#L296)
The fact it works on simulator is an accident, present on [these lines](https://github.com/naoufal/react-native-payments/blob/5b45f79452009f7f48a6d3e762db885f47d67357/packages/react-native-payments/lib/js/PaymentRequest.js#L307)
```js
return Object.assign({}, details, {
    paymentData: null,
    serializedPaymentData
});
```
Calling `Object.assign` copies whatever is present in `details` object and passes it further.
Unfortunately, for real device, returned values are hand picked.

In both cases, return values should be hand picked to make sure they are equal in shape and/or values.

I am aware of #21 PR, I will try to build on that (unfortunately found the PR after my fix)

**Offtopic:**
Apple review passed, this lib is definitely safe for work!

**Comment by Andreyco** [comment]
Several questions... Should we have access to `serializedPaymentData`? Isn't it sufficient to keep original/unserialised data?

**Comment by Andreyco** [comment]
PR provided, open to discussion.

**Comment by naoufal** [comment]
Just getting to this now.

I decided to expose `serializedPaymentData` so that users always have access to the original Apple Pay response.

Separately, I don't parse it on the native side, because the bridge serializes it before sending it over to JS.

**Comment by Andreyco** [comment]
> I decided to expose serializedPaymentData so that users always have access to the original Apple Pay response.

Deserialising that data does not destroy any of original response, correct?
