### ISSUE TITLE
Could not receive Apple Pay paymentResponse in real device

### ISSUE THREAD

**Issue by AwesomeDracula** [naoufal/react-native-payments#332]
![Screen Shot 2021-09-28 at 17 04 25](https://user-images.githubusercontent.com/52280169/135067031-4640cf86-0290-4e38-af57-b193a5691f0a.png)

I apply this code and it still works good in simulator (but cannot use test card with Apple Pay

![Simulator Screen Shot - iPhone 11 - 2021-09-28 at 17 07 32](https://user-images.githubusercontent.com/52280169/135067441-d4345395-77ff-4340-9330-d6246c267dbb.png)
)

But when I run on iOS device, nothing happens on paymentRequest.show().then(). After I tap out to hide Apple Pay, the catch function is executed. The message I received was the same as paymentResponse.complete('fail') though I apply 'success' in the code. What could make this happen?

**Comment by oleksiizhuk** [comment]
I have the same problem; 
i catch err -` ERR [Error: AbortError]`
