### ISSUE TITLE
The linked library 'libPods-App.a' is missing one or more architectures required by this target: x86_64

### ISSUE THREAD

**Issue by serhii-baraniuk** [naoufal/react-native-payments#340]
I have the error right after I did `pod install`

`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening App.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace App.xcworkspace -configuration Debug -scheme App -destination id=55E55753-96FA-4821-9670-3400AC22A38F

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: d4f486a188a3560bd1f9cd732389ebc5
Build description path: /Users/xxx/Library/Developer/Xcode/DerivedData/App-fwwnwxuqnowlrbcwruxoaxpomdwh/Build/Intermediates.noindex/XCBuildData/d4f486a188a3560bd1f9cd732389ebc5-desc.xcbuild

note: Build preparation complete
note: Building targets in parallel
/Users/xxx/github/App/ios/App.xcodeproj: error: The linked library 'libPods-App.a' is missing one or more architectures required by this target: x86_64. (in target 'App' from project 'App')`

**Comment by andreevova** [comment]
Open your **Podfile** and add to **post_install do |installer|**:

installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end

In the end, for me, it looks like this:

post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
