### ISSUE TITLE
[iOS] Provide API for PKPaymentButton

### ISSUE THREAD

**Issue by Andreyco** [naoufal/react-native-payments#36]
Provide API for PKPaymentButton to help developer render Guidelines compliant payment button. Yes, Apple insist on visuals, let's make our lives easier.

This is WIP, PR coming soon

**Comment by miracle2k** [comment]
@Andreyco I was thinking on working on this as well. Did you make any progress?

**Comment by Andreyco** [comment]
Sure. Hope to post progress on this in couple of days. I will open PR, so that anyone can contribute if willing to.

**Comment by iamai74** [comment]
@Andreyco we are waiting your PR =)

**Comment by Andreyco** [comment]
Guys, sorry for inactivity. I am getting back to work on this module!

**Comment by Andreyco** [comment]
Resolve via #84
