### ISSUE TITLE
Make it easier to check if native payments are available

### ISSUE THREAD

**Issue by miracle2k** [naoufal/react-native-payments#41]
In my case, any way, the API as it currently is, requiring me to construct a PaymentRequest to check if Apple Pay or Android Pay are available is a bit cumbersome. It's not necessarily the natural flow, where I would simply want to know if ApplePay is supported before I show the button, and *then* build the payment request.

I'd like to see a static, non-standard method, maybe `PaymentRequest.nativePaymentsAvailable`, that simply gives that answer. On iOS, it seems it's a static flag anyway. On Android, we might call ``IsReadyToPayRequest`` without any filter.

**Comment by Andreyco** [comment]
I suggest exporting helper method from module itself. Let's keep `PaymentRequest` API as clode as possible to specification.

**Comment by naoufal** [comment]
I agree with Andrey, I would defer to the Payment Request API for this. 

You can go under the hood and access the ReactNativePayments native module. But since it isn't an official API theres no guarantee that it'll continue to work.
