### ISSUE TITLE
Is it working with Stripe Connect?

### ISSUE THREAD

**Issue by christoribeiro** [naoufal/react-native-payments#52]
@Andreyco ?

**Comment by Andreyco** [comment]
As I am not the one who wrote this lib from scratch and to be honest I cannot confirm. So far, I only used Braintree (business requirement). I don't know details about "Stripe Connect", but "Stripe" is supported via [addon](https://github.com/naoufal/react-native-payments/tree/master/packages/react-native-payments-addon-stripe).

Will look into Stripe Connect to find out more and maybe @naoufal could clarify.

**Comment by naoufal** [comment]
@christoribeiro Not sure what Stripe Connect is. But I doubt they'd develop a different SDK for it. 

Might be worth looking into it if you need it and reporting back. 

Closing since this isn't an issue with the lib.
