### ISSUE TITLE
Does not work well with react-native-navigation on iOS

### ISSUE THREAD

**Issue by shivawu** [naoufal/react-native-payments#53]
Because of this TODO item: https://github.com/naoufal/react-native-payments/blob/master/packages/react-native-payments/lib/ios/ReactNativePayments.m#L60

When using react-native-navigation, it's possible that we add on more views using things like `showModal`, so the root controller has already presented another view controller, which results in a warning like 

```
Warning: Attempt to present <PKPaymentAuthorizationViewController: 0x12de27c90>  on <RCCTabBarController: 0x12887cc00> which is already presenting <RCCNavigationController: 0x1281eb200>
```

And the apple pay view will just not show up.

**Comment by peterhoang064** [comment]
I had same issue. Did you resolve it yet? @shivawu

**Comment by 6ewis** [comment]
@shivawu did you fix your issue? I'm considering using react-native-payments

**Comment by shivawu** [comment]
I did, but it's hacky:
1. Either you have to guarantee that there's no upper view controller on top of the root one, then it can show correctly
2. Change the code to be something like `lastModalPresenterViewController` in RCCManageModule.m (from react-native-navigation), which walks through the view controller stack and find the top one, and then present the view on top of that one. This would work, but involving changing the code.

**Comment by Andreyco** [comment]
Hello guys, do you have interest in helping us to improve integration with native navigation solutions? We will be glad to assist you ;)

**Comment by jariwalabhavesh** [comment]
I am facing same issue? any update on that

**Comment by Andreyco** [comment]
v0.7.0 correctly displays payment sheet on top of view hierarchy, even over native modals. Please, give it a try
