### ISSUE TITLE
Exception 'Application tried to present a nil modal view controller on target <UIViewController: 0x1037136a0>.' was thrown while invoking show on target ReactNativePayments with params (     3771 )

### ISSUE THREAD

**Issue by peterhoang064** [naoufal/react-native-payments#54]
My environment:
"react-native": "^0.50.3",
"react-native-payments": "^0.3.1",
Xcode: 9.1
Can anyone please help me?

**Comment by Andreyco** [comment]
Duplicate of #24 
If you think issue is not duplicate, provide more info.
