### ISSUE TITLE
Android Pay ReactNativePayments is undefined 

### ISSUE THREAD

**Issue by wgltony** [naoufal/react-native-payments#56]
![image](https://user-images.githubusercontent.com/12904760/34755532-975dc236-f592-11e7-8f8b-d99ce8149c93.png)

Every time I click Android pay button, it will show this error message. Please help. 

 "react": "16.0.0",
 "react-native": "^0.51.0",
 "react-native-payments": "^0.3.1",
 "react-native-payments-addon-braintree": "^4.8.4-1",
 "react-native-payments-cli": "^0.2.0",

dependencies {
    compile project(':react-native-navigation')
    compile project(':react-native-braintree-xplat')
    compile project(':react-native-config')
    compile project(':react-native-payments')
    compile project(':react-native-maps')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(":react-native-navigation")
    compile 'com.google.android.gms:play-services-wallet:11.4.0'
    compile 'com.android.support:support-v4:24.1.1'
    compile 'com.android.support:appcompat-v7:24.1.1'
}

<meta-data
       android:name="com.google.android.gms.wallet.api.enabled"
       android:value="true" />

**Comment by gianpieroc** [comment]
Did you have a solution for this?

**Comment by wgltony** [comment]
My issue was solved and you might want to check whether you have successfully linked package. Also make sure you have import packages in MainApplication.java file.

On Jan 24, 2018, at 1:28 PM, Gianpiero Costanza <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you have a solution for this?
