### ISSUE TITLE
Google Pay

### ISSUE THREAD

**Issue by wgltony** [naoufal/react-native-payments#57]
Since Google no longer enables new Android Pay API now, do you plan to support Google Pay recently? Thanks.

**Comment by Andreyco** [comment]
Yes, Google Pay is considered but we could definitely use some of your help. Willing to open PR?
Let's start with simple ideas, describing current state of payments on Android platform (as iOS user I am getting lost, thanks to frequent re-brandings/renaming of payments on Android platform).

Let's initiate conversation prior to writing code ;)

**Comment by Andreyco** [comment]
Let's move discussion to #46
