### ISSUE TITLE
Xcode (v 9.2) build fails after linking stripe

### ISSUE THREAD

**Issue by David-Owen-Walker** [naoufal/react-native-payments#58]
![screen shot 2018-01-17 at 3 20 06 pm](https://user-images.githubusercontent.com/4590521/35065842-7e7ece6c-fb9c-11e7-8069-7dd1c7411379.png)

The linking seems to have worked correctly, and carthage is installed (via brew), but the pictured build step fails with the error

`Failed to read file or folder at /Users/David/Documents/app-name/ios/../node_modules/react-native-payments-addon-stripe/Carthage/Build/iOS/Stripe.framework`

And indeed upon checking that location there is no folder called Carthage.

**Comment by Andreyco** [comment]
you should run `carthage update` or `carthage install` (don't remember) from `../node_modules/react-native-payments-addon-stripe`

**Comment by David-Owen-Walker** [comment]
`carthage update` worked perfectly. Much appreciated!

**Comment by Andreyco** [comment]
This is know "issue" to me and yeah, it's frustrating. I will try to come up with solution for this.

**Comment by tehong** [comment]
Encountered this problem.  It would be good to have a more elegant solution.

**Comment by Andreyco** [comment]
As a last resort, I am thinking about installing addon outside of `node_modules` and add instructions to docs.

Do you suggest any solution, that would allow us to keep all dependencies in `node_modules`?

**Comment by tehong** [comment]
Would like to keep in the node_modules, but at this stage, what you suggest might be a better solution.  

Another possible solution is to add another pre-build shell script and run ```cathage update``` prior to the ios/android build if the ```…/Carthage/…``` directory is not there?  

Also, I'm not a expert with the npm install, but looks like it might be possible to put into a npm script in the package.json manually that runs after "postinstall" of a "npm install" or a "yarn add". That script can run the ```cathage update``` in the ```./node_modules/react-native-payments-addon-stripe/``` directory afterwards.   See https://docs.npmjs.com/misc/scripts.
