### ISSUE TITLE
Works with expo?

### ISSUE THREAD

**Issue by MichelDiz** [naoufal/react-native-payments#59]
Expo.io has some issues when is a native component.

**Comment by Andreyco** [comment]
Nope. In order to make this work with Expo, you need to eject/detach.
Expo does not allow to run any native code not bundled with Expo SDK

**Comment by MichelDiz** [comment]
Would it be possible and feasible to send a request to Expo? This is a very important resource. And probably there are no similar solutions natively by the Expo.

**Comment by Andreyco** [comment]
Sure, open the request on Expo repo/site ;)
