### ISSUE TITLE
Setup Android link goes to 404

### ISSUE THREAD

**Issue by LukasNavickas** [naoufal/react-native-payments#67]
"Setup Android" link on the documentation goes nowhere (404)

**Comment by Andreyco** [comment]
Could you specify exact link and provide working one?
PR welcome! Thanks

**Comment by Norfeldt** [comment]
Please see my answer to #79 (where the link is at). 

I'm on mobile so can't do a PR and did a search in the Google developer docs - it's difficult to know what would be the right end destination.

Is this it?

 https://developers.google.com/pay/api/android/guides/setup

**Comment by Andreyco** [comment]
Docs are updated
