### ISSUE TITLE
react-native-payments-addon-stripe example doesn't work with Android Pay

### ISSUE THREAD

**Issue by LukasNavickas** [naoufal/react-native-payments#68]
react-native-payments-addon-stripe example doesn't work with Android Pay.  After executing "yarn react-native-payments-cli -- link stripe", cmd asks of the location for Xcode, but I'm developing using Android Studio only. 
Can't get it work using android pay.

**Comment by Andreyco** [comment]
Stripe, Braintree and other gateways work by default on Android. You do not have to link them for Android! ;)
