### ISSUE TITLE
Does not work with react-navigation

### ISSUE THREAD

**Issue by jthink0228** [naoufal/react-native-payments#72]
both Android / IOS,
apple pay / android pay  view will  not show up.

how to fixed the issue ?

many thanks

**Comment by Amurmurmur** [comment]
@jthink0228 Make sure you setup apple pay/android pay options object correctly.

It wonts show it there are errors in the setup objects for each payment system.

It has nothing to do with the navigation solution you use since it calls native payment uis for each platform.

**Comment by Andreyco** [comment]
Could you please install v0.7.0? There were changes that makes it possible to display Payment sheet on top of native modal - which was not possible before.
