### ISSUE TITLE
The link of guide on android pay setup is not working

### ISSUE THREAD

**Issue by Pianist038801** [naoufal/react-native-payments#79]

**Comment by Andreyco** [comment]
Which one? Could you provide more details?

**Comment by Norfeldt** [comment]
The one in the README at

'''
Setting up Apple Pay/Android Pay
Before you can start accepting payments in your App, you'll need to setup Apple Pay and/or Android Pay.

Apple Pay
Register as an Apple Developer
Obtain a merchant ID
Enable Apple Pay in your app
Apple has a documentation on how to do this in their Configuring your Environment guide.

Android Pay
Add Android Pay and Google Play Services to your dependencies
Enable Android Pay in your Manifest
Google has documentation on how to do this in their Setup Android Pay guide.
'''

**Comment by Andreyco** [comment]
Docs are updated
