### ISSUE TITLE
Support for Android Pay

### ISSUE THREAD

**Issue by sahil6111** [naoufal/react-native-payments#8]
Is there any possibility for implementing/Support **Android Pay** in future ?

**Comment by andrerfneves** [comment]
Correct me if I'm wrong, but I believe @naoufal is aiming to support a couple more payment providers before adding Android Pay given the different nuances of the APIs.

**Comment by naoufal** [comment]
That's right @andrerfneves. 

I have a plan for rolling out Android pay and potentially other methods of payment that I'll write draft out soon. 

Stay tuned.

**Comment by OpenKompani** [comment]
@naoufal  How soon would android pay support become available. Can't wait to use this  in my next app. I saw your presentation on Chain React was so impressed

**Comment by naoufal** [comment]
Thanks @OpenKompani -- glad you enjoyed it.

I started work on this last week, but had to put things on hold this week.  I plan on jumping back on it in a week or two.

**Comment by edenvicary** [comment]
I'm keen on the Android support, is there anything you need that could help unleash you fully in it?

**Comment by naoufal** [comment]
Sup fam #17

**Comment by MichelDiz** [comment]
Nice! xD Now we Talking.

Let me ask you something. I had seen a while ago a project like yours that had support for payments via the Web - Only web. I think it had to do with WebView.
Could your project have web support in future? For example ReactJS or even something like "React Native for Web" or "react-native-windows" and maybe, who knows, Electron?

Adding brackets of type your project would be a reference.

**Comment by andrerfneves** [comment]
@MichelDiz if the Payment API is consistent throughout all those platforms, the above should be possible. Although probably only on the `react-native` side (not electron or reactjs). This is also an initiative that the community could get behind instead of leaving it up to the maintainer of the package.

**Comment by andrerfneves** [comment]
Great work @naoufal!!

**Comment by Pianist038801** [comment]
Hi, @naoufal. Thanks in advance for this nice package.
Btw I need Android Pay in my current react native app.
Is not it implemented yet? I saw from your message that you would start in a week or two.
