### ISSUE TITLE
Unhandled Promise Rejection (id: 0) Error: AbortError

### ISSUE THREAD

**Issue by alexd16** [naoufal/react-native-payments#82]
Hi, 

I am trying to setup apple pay payments with react-native-payments in a project but I am having some trouble getting this to work consistently.

I have copied the basic code from the examples:

    handleBuy() {
        const methodData = [{
            supportedMethods: ['apple-pay'],
            data: {
                merchantIdentifier: '....',
                supportedNetworks: ['visa', 'mastercard', 'amex'],
                countryCode: 'US',
                currencyCode: 'USD'
            }
        }]

        const displayItems = [{
            label: 'Movie Ticket',
            amount: {
                currency:'USD',
                value: '15.00'
            }
        }]

        const total = {
            label: 'Sirva',
            amount: {
                currency: 'USD',
                value: '15.00'
            }
        }

        const details = {
            id: 'example',
            displayItems,
            total
        }

        const pr = new PaymentRequest(methodData, details);
        pr.show()
            .then(paymentResponse => paymentResponse.complete('success'))
    }

When I click the Buy Button, the apple pay modal shows up with the processing spinner going until it errors (with the exclamation red icon instead of the spinner ).
In the logs I get:
Error: AbortError
Error: AbortError
    at PaymentRequest._closePaymentRequest (blob:http://localhost:8081/a0a23916-b213-491a-8451-6c1d6b137767:117513:37)
    at RCTDeviceEventEmitter.emit (blob:http://localhost:8081/a0a23916-b213-491a-8451-6c1d6b137767:22462:37)
    at MessageQueue.__callFunction (blob:http://localhost:8081/a0a23916-b213-491a-8451-6c1d6b137767:8521:44)
    at blob:http://localhost:8081/a0a23916-b213-491a-8451-6c1d6b137767:8291:17
    at MessageQueue.__guardSafe (blob:http://localhost:8081/a0a23916-b213-491a-8451-6c1d6b137767:8483:11)
    at MessageQueue.callFunctionReturnFlushedQueue (blob:http://localhost:8081/a0a23916-b213-491a-8451-6c1d6b137767:8290:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:72:58

And I get a crash notice from mac os saying the "PassbookUIService quit unexpectedly"

At some point I was able to get this working, but it's pretty inconsistent and right now is not working. I am not sure how to debug since I didn't change anything.
Even when it's working I still get the same warning in the logs and the PassbookUI errors.

I am testing this on a simulator, does this have any impact?
Any idea on how to fix this or what the problem might be?

**Comment by Andreyco** [comment]
Do you have possibility to test on real device? It is possible device might behave a bit differently

**Comment by mrcflorian** [comment]
I'm getting a very similar error on my iPhone X. I'm also using just the basic example from the docs.

```
21:34:42 [exp] [Unhandled promise rejection: Error: AbortError]
- node_modules/react-native-payments/lib/js/PaymentRequest.js:377:42 in _closePaymentRequest
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:182:12 in emit
- ... 5 more stack frames from framework internals
```

**Comment by mrcflorian** [comment]
Never mind. I forgot to update the merchantIdentifier in paymentData. It works well now.

**Comment by dpetkevich** [comment]
I'm having the same issue as OP. @alexd16 did you find a fix?

**Comment by VaseemDeveloper** [comment]
Hi mrcflorian
I am getting the same error (Unhandled promise rejection: Error: AbortError) at line - 83 at this file - https://github.com/WebKit/webkit/blob/master/Websites/webkit.org/demos/payment-request/demo.js

const response = await paymentRequest.show();
response.complete("success");

Can you please tell me where should i update the merchant id.
I am using all the 5 files downloaded from here - https://github.com/WebKit/webkit/tree/master/Websites/webkit.org/demos/payment-request

**Comment by alexd16** [comment]
@dpetkevich Hey, sorry for the late reply.

Yeah I was able to get it to work, but to be honest I don't have a magic solution.
I just went to xcode messed with the apple pay setting, by disabling and enabling again. Did the same for the merchant ID: disable it and enabled it again. After that it started working again consistently and never stopped.

I know that this is not really a solution and that's why I didn't post it here. Hope you have it fixed by now.

**Comment by i-khreptak** [comment]
Yes, this bug can to be when you did not turn on Apple pay in your app in xCode
**Select project => Capabilities => And select Apple pay**

**Comment by b3hz4d** [comment]
I had this issue too.
It's because your linking with react native having problem, check your MainApplication.java and be sure that react native payments included

**Comment by l1fe** [comment]
I have the same issue. I turned on Apple pay in *Capabilities* and specified correct merchant id in `METHOD_DATA` which is registered in Apple Developer. Any other options?

**Comment by uday5162** [comment]
Hey guys,
Did any one got it to working in production, for me everything working fine in simulator but with sandbox account getting this error. Tried all the suggested changes.
