### ISSUE TITLE
importing react-native-payments -- best practices

### ISSUE THREAD

**Issue by peacechen** [naoufal/react-native-payments#83]
The documentation says:

> Once Apple Pay/Android Pay is enabled in your app, jump into your app's entrypoint and make the PaymentRequest globally available to your app.
> 
> ```
> // index.ios.js
> global.PaymentRequest = require('react-native-payments').PaymentRequest;
> ```
> 

Setting globals is generally considered bad practice.  It would be better to simply import it wherever needed:
```
// AnyFile.js
import { PaymentRequest } from 'react-native-payments';
```

Will that work for this library, or is there something needed by the library to be in global?

**Comment by Andreyco** [comment]
It will definitely work of course.
By assigning global you are telling you want to use this particular implementation.

I will dig into this and find a better alternative as you suggest. Keeping this one open.
If you have ideas about implementation details, lets talk about them

**Comment by peacechen** [comment]
The risk with using global is if another library happens to use the same global name, one will stomp over the other.  Speaking from experience ;)

**Comment by Andreyco** [comment]
I agree with you. See MooTools, speaking of you as well 😂

**Comment by Andreyco** [comment]
Looked at the examples and the only reason for global here is that Common app (exaples/common) works on web and native as well. 
Ofc, if you only need PaymentRequest in native, do import PR from module
`import { PaymentRequest } from 'react-native-payments';`
