### ISSUE TITLE
TypeError: Cannot read property 'supportedGateways' of undefined

### ISSUE THREAD

**Issue by SoyAndresHernandez** [naoufal/react-native-payments#88]
Hi guys,
I have this error when trying to import the library.
`TypeError: Cannot read property 'supportedGateways' of undefined `
<img width="440" alt="screen shot 2018-05-22 at 6 30 23 pm" src="https://user-images.githubusercontent.com/15066510/40395574-5c30126c-5dee-11e8-88ee-605526738c0f.png">

PODFILE>

`# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '8.0'
target 'New Stand' do
	project 'New Stand.xcodeproj'
	pod 'GoogleCloudMessaging', '~> 1.2.0'
	pod 'GGLInstanceID', '~> 1.2.1'
	pod 'lottie-ios', '~> 2.5.0'
	pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    'RCTImage',
    'RCTLinkingIOS'
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNSVG', :path => '../../node_modules/react-native-svg'
  pod 'BVLinearGradient', :path => '../../node_modules/react-native-linear-gradient'
  pod 'react-native-camera', path: '../../node_modules/react-native-camera'
  pod 'ReactNativePayments', path: '../../node_modules/react-native-payments/lib/ios'
end
`

Thanks..

**Comment by Andreyco** [comment]
current version of RNP has invalid Podspec file. I will try to review existing PR asap. Until then, link without cocoapods
