### ISSUE TITLE
No mention of PaymentResponse.complete  in the manual

### ISSUE THREAD

**Issue by frmrgr** [naoufal/react-native-payments#9]
Docs of this library say nothing about calling complete method on PaymentResponse instance. However, without this, the payments dialog just freezes in processing mode. Can you please add an example of how to use the library correcly?

**Comment by naoufal** [comment]
Hi @frmrgr,

There are actually a few examples in the project that you're welcome to checkout. 

https://github.com/naoufal/react-native-payments/tree/master/examples

There are also documentation on each API. You can find docs on PaymentResponse here:

https://github.com/naoufal/react-native-payments/blob/master/docs/PaymentResponse.md#paymentresponse

Let me know how the docs can be improved and even better, feel free to submit a PR.

**Comment by frmrgr** [comment]
Thank you. For some reason promise returned from PaymentResponse.complete method never resolves nor fails, but that is offtopic here.

**Comment by naoufal** [comment]
@frmrgr — it should resolve to undefined as per the spec. 

https://www.w3.org/TR/payment-request/#complete()-method

**Comment by frmrgr** [comment]
It should, but for me it doesn't. Maybe it's because I test it in simulator, it might work correctly on the device.

**Comment by naoufal** [comment]
@frmrgr Added a section on dismissing the `PaymentRequest` in the main README.

https://github.com/naoufal/react-native-payments#dismissing-the-payment-request-1
